name: workflow

on:
  schedule:
    - cron:  '15 * * * *'

# on:
#   repository_dispatch:
#     type: after_saving_wordpress
  # push:
  #   branches:
  #     - master



jobs:
  deploy: # ジョブ名(名前は任意)
    runs-on: ubuntu-latest
    timeout-minutes: 10 # デフォルトは360（6時間）のため短い時間で設定しておく
    env:
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm ci

      - name: Next Generate
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          
      - name: S3 sync
        working-directory: static-files
        run: aws s3 sync ./out s3://${{ secrets.AWS_BUCKET_NAME }} --delete --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --exclude "README.md"

